### PR TITLE
Update credit scoring example

### PR DESCRIPTION
**Pull request by AbSsEnT**
## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Review by alexcombessie — CHANGES_REQUESTED** [review]
Couple of changes needed:
1. Can you remove the cell output of the notebook for everything except the scan results?
2. Can you update data-types/tabular/index.md?

**Comment by AbSsEnT** [comment]
> Couple of changes needed:
> 
> 1. Can you remove the cell output of the notebook for everything except the scan results?
> 2. Can you update data-types/tabular/index.md?

+

**Comment by AbSsEnT** [comment]
@alexcombessie I fixed what you have asked me about.

**Review by alexcombessie — APPROVED** [review]
LGTM!

**Pull request merged**
