### PR TITLE
Fixed issue where selected tab was not highlighted by default

### PR DESCRIPTION
**Pull request by kevinmessiaen**
## Description

Fixed issue where selected tab was not highlighted by default

## Type of Change

- [x] 🔧 Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.

### CODE REVIEW

**Review by Googleton — COMMENTED** [review]
Code is good for me but it seems like integration tests fail

**Comment by kevinmessiaen** [comment]
> Code is good for me but it seems like integration tests fail

I fixed it, I think it was an issue coming from `main`

**Comment by Googleton** [comment]
I see your fix, I'm not sure if changing the test is proper in this case. Shouldn't we look at the test data instead and figure out why it breaks now ? Maybe it's something trivial that doesn't require changing the test itself ?

**Comment by Googleton** [comment]
> > I see your fix, I'm not sure if changing the test is proper in this case. Shouldn't we look at the test data instead and figure out why it breaks now ? Maybe it's something trivial that doesn't require changing the test itself ?
> 
> Actually the test isn't deterministic: `project.getDatasets().stream().findFirst();` will always return any of available dataset randomly and some does not have target by default

Yea that's true. Should we consider getting a specific demo project for this test?

**Comment by kevinmessiaen** [comment]
> > > I see your fix, I'm not sure if changing the test is proper in this case. Shouldn't we look at the test data instead and figure out why it breaks now ? Maybe it's something trivial that doesn't require changing the test itself ?
> > 
> > 
> > Actually the test isn't deterministic: `project.getDatasets().stream().findFirst();` will always return any of available dataset randomly and some does not have target by default
> 
> Yea that's true. Should we consider getting a specific demo project for this test?

I've selected one with a feature by default.

**Review by andreybavt — APPROVED** [review]

**Pull request merged**
