### PR TITLE
Added MistralEmbedding

### PR DESCRIPTION
**Pull request by kevinmessiaen**
## Description

Added MistralEmbedding to allow running the rag toolkit

TODO:
- [x] 🚀 Add MistralEmbedding class
- [ ] 📚 Update doc
- [ ] 🧪 Add tests

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hey @kevinmessiaen - Is this PR ready for review?

**Comment by alexcombessie** [comment]
Hey @kevinmessiaen - any news on this PR?

**Comment by kevinmessiaen** [comment]
> Hey @kevinmessiaen - any news on this PR?

We will be working on implementing [litellm](https://github.com/BerriAI/litellm) instead which will allow to work with most provider without custom code

**Comment by alexcombessie** [comment]
Clear, thanks!

**Pull request closed without merging**
