### PR TITLE
model upload unit-tests for pre-2.0.0 API

### PR DESCRIPTION
**Pull request by rabah-khalek**
## Description

YouTrack: https://giskard.youtrack.cloud/agiles/121-12/current?issue=GSK-336

## Related Issues

- https://github.com/Giskard-AI/giskard/issues/374

TODO:
- [ ] merge this branch to https://github.com/Giskard-AI/giskard/pull/618 and make sure the tests pass

### CODE REVIEW

**Comment by andreybavt** [comment]
@rabah-khalek I think it's best to create a new branch from `feature/new-upload-api` (call it `enhancement/new-upload-api-tests`), merge `GSK-336_model-API` into it and make necessary changes to allow the new tests to pass. Then you can create a new PR from `enhancement/new-upload-api-tests` to `feature/new-upload-api`

**Comment by rabah-khalek** [comment]
@andreybavt, I moved the unit-tests to the corresponding branches in the new API. But I would still like to merge this one, to keep track of the issues we were having before. I'm going to mark it as ready to review this one.

**Comment by andreybavt** [comment]
@rabah-khalek, have you copied all of the tests from this branch to the `*-tensorflow` and `*-pytorch` branches? Should we close this PR?

**Comment by rabah-khalek** [comment]
Yes i took what i needed. But can't we merge this one and mark the failing unit tests skipped? Just for bookkeeping.

**Comment by andreybavt** [comment]
@rabah-khalek , it'll at least require the test files refactoring to make them PEP8 compatible. If you're saying that everything is copied to other branches we can close this PR then

**Comment by rabah-khalek** [comment]
ok done.

**Comment by rabah-khalek** [comment]
for some reason that I'm still investigating, one of these libraries: `h2o torch transformers tensorflow torchtext torchdata` is causing `test_upload.py` to fail.

**Comment by andreybavt** [comment]
@rabah-khalek , do we close this PR?

**Comment by rabah-khalek** [comment]
Yes.

**Pull request closed without merging**
