### PR TITLE
Feature/gsk 1243 project export doesnt work

### PR DESCRIPTION
**Pull request by kevinmessiaen**
## Description

- [x] Fixed recursive issues
- [x] Export tests/slicing/transformation
- [x] Fix issue with parameters

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by Inokinoki** [comment]
Is this still WIP?

I could review if it's ready and up-to-date

**Comment by kevinmessiaen** [comment]
@Inokinoki This PR needs to be updated with main, the export might be broken due to modification of database schema. It was initially on hold due to ongoing refactor of artifacts but we can merge it.

**Comment by kevinmessiaen** [comment]
@Inokinoki I've updated the branch and the export seems to be working with latest modification

**Comment by Inokinoki** [comment]
LGTM
Tested locally, working perfectly!

In addition, should we display something like "export failed" when getting 500 in frontend side? I can add it if you do not have time

**Comment by Inokinoki** [comment]
I tried to improve the code smell stuff from SonarLint. But I am not sure how to implement the comparison in the remaining one.

**Comment by kevinmessiaen** [comment]
> I tried to improve the code smell stuff from SonarLint. But I am not sure how to implement the comparison in the remaining one. Could @kevinmessiaen please review them?

Sure I fixed the error. In this case we had to override it to make sure two instance of `Callable` with same `uuid` but a different class (eg. `SlicingFunction` and `TransformationFunction`) are not interpreted has `equals`.

**Comment by Inokinoki** [comment]
LGTM

**Pull request merged**
