### PR TITLE
[GSK-1235] Fix segmentation fault problems when running pytest

### PR DESCRIPTION
**Pull request by mattbit**
Should solve the problems with fixtures `tripadvisor` and `fraud_detection` when running pytest locally on certain environments. @AbSsEnT could you check that this also solves the problem on your machine?

### CODE REVIEW

**Review by andreybavt — CHANGES_REQUESTED** [review]

**Comment by AbSsEnT** [comment]
@mattbit will check it in 20 minutes

**Comment by AbSsEnT** [comment]
I am still getting serrault for the `fraud_detection` fixture.

**Comment by andreybavt** [comment]
@AbSsEnT , can you test it again to see if you still get a segfault?

**Comment by AbSsEnT** [comment]
> @AbSsEnT , can you test it again to see if you still get a segfault?

@andreybavt still getting segfault for the fraud_detection fixture.

**Comment by mattbit** [comment]
> @mattbit , do we still need to make changes to the lightgbm version to solve Mykyta's issue?

It would be useful because it removes a few unnecessary steps (download of stopwords which are not used), avoids downloading and initializing DistilBERT at import time, and frees memory since model is now loaded in the test scope.

**Review by andreybavt — APPROVED** [review]

**Pull request merged**
