### PR TITLE
[GSK-1199] Implement websocket to get worker status

### PR DESCRIPTION
**Pull request by henchaves**
## Description

The idea of this PR is to implement a WebSocket to provide a channel through which the backend can send the ML Worker status without any request from the front. 

This improvement will be divided into two phases:
1- Implement WebSocket on back and frontend, send the worker status periodically from Spring app, and update Vue components to use websocket instead of store. **(CURRENT PR)**
2- Make the backend only send a message to the channel when the worker status change, instead of sending it every N seconds. Also, send the last worker status whenever a new subscriber appears.

## Related Issue

[GSK-1199 (available on Linear)](https://linear.app/giskard/issue/GSK-1199/create-websocket-to-get-worker-status)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [x] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

### CODE REVIEW

**Review by andreybavt — CHANGES_REQUESTED** [review]
Generally LGTM, but there should be an NGINX config (`packaging/nginx.conf.template`) modified to also forward WS requests to the backend (the same way we do for http traffic)

**Comment by andreybavt** [comment]
@henchaves on my end I don't get notifications when running Giskard in production mode (in docker).

Also when testing in dev mode I had to use the UI for a bit before I started receiving ML Worker connected/disconnected messages:
- I installed a blank instance
- connected the worker - no notification ❌
- disconnected the worker - no notification ❌
- created project, connected/disconnected worker - no notification ❌
- ran the onboarding code and connected/disconnected worker - no notification ❌
- opened the test suite and connected/disconnected worker - got notification ✅

**Comment by andreybavt** [comment]
Well, it should be enabled on a global level (except for the login page). It's important to know if a worker gets disconnected even if you're not immediately using it

**Comment by henchaves** [comment]
@andreybavt, I added worker notifications for all components inside Main.vue. Can you try again the use cases you mentioned? I tried it on my side, and it's working now.

**Comment by andreybavt** [comment]
@henchaves , sure I'll retest now. Did you try in Docker too?

**Comment by andreybavt** [comment]
I also spotted an unhandled corner case: when you logout (available with a paid license) you don't unsubscribe from the websocket events and thus still continue receiving the notifications 

image

**Comment by henchaves** [comment]
@andreybavt, everything should be working now (including using Docker)

**Comment by andreybavt** [comment]
@henchaves ok, I'm checking again and then it's good to merge

**Comment by andreybavt** [comment]
@henchaves , one other thing I noticed is that the security question isn't solved in this PR. You can connect to this WS endpoint and send/receive STOMP messages from any client without being authenticated

**Comment by andreybavt** [comment]
Once the build passes it should be OK to merge

**Pull request merged**
