### PR TITLE
Feature/GitHub summary

### PR DESCRIPTION
**Pull request by Hartorn**
Experimentation to get better output in summary for python actions

Example with error in test here : https://github.com/Giskard-AI/giskard/actions/runs/6144369253#summary-16669640839

### CODE REVIEW

**Comment by Inokinoki** [comment]
Nice work!
Does this task have already Linear card? I've created a card a few weeks ago, which seems to be related: https://linear.app/giskard/issue/GSK-1650/export-java-and-python-test-reports

**Comment by Hartorn** [comment]
> Nice work! Does this task have already Linear card? I've created a card a few weeks ago, which seems to be related: https://linear.app/giskard/issue/GSK-1650/export-java-and-python-test-reports

The Windows part and CI splitting is in another part, the report part not so much. 
I will reuse your card then

**Comment by andreybavt** [comment]
@Hartorn could you also add a plain list of tests with their status under a collapsible section?
It'll be useful when making sure that a specific test has actually been executed

**Comment by Hartorn** [comment]
> @Hartorn could you also add a plain list of tests with their status under a collapsible section? It'll be useful when making sure that a specific test has actually been executed

Sure, done in the last version !
I've added something close for Gradle, but a bit more basic (still difficult for me to get a hand on Kotlyn script)

**Review by andreybavt — APPROVED** [review]

**Pull request merged**
