### PR TITLE
[GSK-2879][GSK-3300] Technical documentation of Giskard Evaluator in the Giskard doc

### PR DESCRIPTION
**Pull request by Inokinoki**
## Description

@cy-moi has created a full tutorial from the technical aspect. Move it to our doc and polish it.

## Type of Change

- [x] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by Inokinoki** [comment]
> @Inokinoki can you please make the main HuggingFace integration page on its own with 2 cards inside, and 2 sub pages like this: image CleanShot 2024-03-21 at 17 54 51@2x
> 
> Then ill make the changes on the content

I updated it to like

image

because ToC does not want to include `index.md`.

**Comment by cy-moi** [comment]
🎉🎉🎉🎉

**Review by luca-martial — COMMENTED** [review]
@Sakayatsp will take over the review

**Review by Sakayatsp — COMMENTED** [review]
`Once your job has finished, you will be able to find the scan report in the model’s community discussion page.`
Maybe we could add a picture of the tabs to show where the community discussion page is.

**Comment by luca-martial** [comment]
> > `Once your job has finished, you will be able to find the scan report in the model’s community discussion page.`
> 
> Maybe we could add a picture of the tabs to show where the community discussion page is.

Yes good idea for a future improvement, lets merge this for now

**Review by luca-martial — APPROVED** [review]

**Pull request merged**
