### PR TITLE
moved proba calculation from relative to absolute

### PR DESCRIPTION
**Pull request by rabah-khalek**
## Description

I had the disparate impact as ratio of average probabilities, while I believe it should be a sum of them instead.

## Type of Change

- [x] 🥂 Improvement (non-breaking change which improves an existing feature)

### CODE REVIEW

**Comment by andreybavt** [comment]
@rabah-khalek apparently some tests don't pass anymore

**Review by andreybavt — CHANGES_REQUESTED** [review]
there are currently failing unit tests

**Comment by rabah-khalek** [comment]
Yes, I had to change the unit test, because the metric has changed. As for the new metric, I already benchmarked it yet again with the plots in the new article on disparate_impact. Thanks @andreybavt

**Comment by rabah-khalek** [comment]
Upon reflection, i will close this pr, keeping the DI relative.

I thought first that the relative version is not a good representation for small statistical sample. At the same time, the absolute version deviates from the actual definition of disparate impact, i.e ratio of probabilities.

**Pull request closed without merging**
