### PR TITLE
project key : fix incompatible check with generated key from project name

### LINKED ISSUE #96: Auto-generated project key doesn't meet validation
## 🐛 Bug Report

The automatically generated _project key_ replaces spaces with dashes. The _project key_ validation doesn't allow the field to have dashes.

## 🔬 How To Reproduce

1. Open the dashboard and log in with your account;
2. Go to _Projects_;
3. Create a new project;
4. Type a project name containing spaces;
5. **Don't** edit the auto-generated project key;
6. Click on _SAVE_.

### Screenshots

Screen Shot 2022-06-23 at 15 32 35

### PR DESCRIPTION
**Pull request by lodovicoazzini**
## Description

Change validation pattern to comply with the automatic generated key.

## Related Issue

Closes #96

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [x] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [x] I've written tests for all new methods and classes that I created.
- [x] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hi @lodovicoazzini,

I see that many changes in the file are related to differences in code style formatting. Could you revert those changes to keep the PR only about the one line with the pattern change?

Thanks,

Alex

**Comment by alexcombessie** [comment]
Thanks @lodovicoazzini !

For clarity, could you share a short video clip of the bug?

**Comment by alexcombessie** [comment]
Hi @lodovicoazzini,

My bad, forget my previous message. You have clarified everything in your issue #96

**Comment by lodovicoazzini** [comment]
Hi @alexcombessie! The video was already in production. If not needed I will shut it down.

**Comment by alexcombessie** [comment]
Thanks @lodovicoazzini I can reproduce and I confirm your PR fixes the issue!

**Comment by lodovicoazzini** [comment]
@alexcombessie glad to help!
I updated the tests for `ProjectService` in `AdminProjectControllerIT` to reflect the changes in the project key format.

**Pull request merged**
