### PR TITLE
[GSK-2569] Scanner plugin for custom detectors

### PR DESCRIPTION
**Pull request by bmalezieux**
## Description

Adding a new Scanner object to handle custom models, datasets and list of detectors. This makes the integration of plugin tools easier for users.

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [x] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by mattbit** [comment]
Uhm, do we need to duplicate this code? What are plugin tools? I can't see the full picture here, but let me know if I can help with the scan architecture.

**Review by rabah-khalek — CHANGES_REQUESTED** [review]
Thanks @mattbit, this is still a draft, wip. 

@bmalezieux , since the scanner we need is more basic and more permissive, I would suggest to do it the other way around, create a `BaseScanner` that isn't giskard-oriented (no validation, nothing related to `BaseModel`, or `Dataset`) just a skeleton that the `giskard.Scanner` would inherit from and extend. This should help reducing the duplications. 

We will then use the `BaseScanner` for our purposes.

We will also need to modify the factory method `giskard.scan`, here there're multiple options:
- splitting the API into `scan` and `custom_scan` (that takes custom detectors)
- modifying the `scan` API to take optionally detectors.
let me think about the latter a bit more.

**Comment by rabah-khalek** [comment]
@bmalezieux feel free to suggest architectural changes if they help abstract the code. 

For instance the current:
```py
class Scanner:
    def _print_execution_summary(self, model, issues, errors, elapsed):
        print(
            f"Scan completed: {len(issues) or 'no'} issue{'s' if len(issues) != 1 else ''} found. (Took {datetime.timedelta(seconds=elapsed)})"
        )
        if model.is_text_generation:
            measured = self._get_cost_measure()
            print(COST_SUMMARY_TEMPLATE.format(**measured))
        if errors:
            warning(
                f"{len(errors)} errors were encountered while running detectors. Please check the log to understand what went wrong. "
                "You can run the scan again with `raise_exceptions=True` to disable graceful handling."
            )
```

can be changed into:
```py
class BaseScanner:

    def analyze(
        self, ...
    ) -> ScanReport:
        # etc...
        if verbose:
            self._print_execution_summary(model, issues, errors, elapsed)
            self._warn(errors)

   def _warn(self, errors):
        if errors:
            warning(
                f"{len(errors)} errors were encountered while running detectors. Please check the log to understand what went wrong. "
                "You can run the scan again with `raise_exceptions=True` to disable graceful handling."
            )

    def _print_execution_summary(self, model, issues, errors, elapsed):
        print(
            f"Scan completed: {len(issues) or 'no'} issue{'s' if len(issues) != 1 else ''} found. (Took {datetime.timedelta(seconds=elapsed)})"
        )
```
```py
class Scanner(BaseScanner):
    def analyze(
        self, ...
    ) -> ScanReport:
        # etc...
        if verbose:
            self._print_execution_summary(model, issues, errors, elapsed)

    def _print_execution_summary(self, model, issues, errors, elapsed):
        super()._print_execution_summary(self, model, issues, errors, elapsed)
        if model.is_text_generation:
            measured = self._get_cost_measure()
            print(COST_SUMMARY_TEMPLATE.format(**measured))
```

The goal is:
- no duplications
- more abstraction
- full backward compatibility

**Comment by bmalezieux** [comment]
This is better in my opinion, even though detectors run method must take features as input to comply with the API. WDYT @rabah-khalek ?

**Pull request closed without merging**
