### PR TITLE
Do not run integration tests on windows

### PR DESCRIPTION
**Pull request by Hartorn**
Slight improvement to not run integration tests on windows
Also avoid re-running not slow tests

### CODE REVIEW

**Comment by mattbit** [comment]
@Hartorn, why?

**Comment by Hartorn** [comment]
> @Hartorn, why?

@mattbit Well, on windows runner, the nightly fails, because the whole workflow is taking more than 360minutes.
This is also linked to the fact we cannot used XDIST with more thant 1 on windows runner, else they run out of memory.

**Comment by mattbit** [comment]
> Well, on windows runner, the nightly fails, because the whole workflow is taking more than 360minutes.

Wait, is it the workflow on Windows that takes >360 min or you mean the combined time of testing on all platforms & python versions?

**Comment by Hartorn** [comment]
> > Well, on windows runner, the nightly fails, because the whole workflow is taking more than 360minutes.
> 
> Wait, is it the workflow on Windows that takes >360 min or you mean the combined time of testing on all platforms & python versions?

The workflow on Windows, including all integrations test, not the combined time.

**Review by andreybavt — APPROVED** [review]
as sub-task to re-enable "slow" tests for windows after investigating why they can't be run with GH runner:

https://linear.app/giskard/issue/GSK-1613/enable-slow-tests-on-windows

**Pull request merged**
