### PR TITLE
feat: set __str__ to use name and id for Dataset and Model

### PR DESCRIPTION
**Pull request by AdriMarteau**
## Description

Define `__str__` for the Dataset and Model classes for more user friendly prints and reports

## Related Issue

[Original discussion](https://github.com/orgs/Giskard-AI/discussions/1723) 

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [x] I've written tests for all new methods and classes that I created.
- [x] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Review by kevinmessiaen — CHANGES_REQUESTED** [review]
Thanks for the work, I only have one remark is that the type of object is not visible:
`test-b55675f8-2ffd-4d7e-92b8-945e40be5b68` can be either a Model or a Dataset.

I believe something like that would be better:
`<giskard.Model name="test" uuid=b55675f8-2ffd-4d7e-92b8-945e40be5b68>`

**Comment by AdriMarteau** [comment]
> Thanks for the work, I only have one remark is that the type of object is not visible: `test-b55675f8-2ffd-4d7e-92b8-945e40be5b68` can be either a Model or a Dataset.
> 
> I believe something like that would be better: `<giskard.Model name="test" uuid=b55675f8-2ffd-4d7e-92b8-945e40be5b68>`

I overloaded the `__str__` method for the moment. I can also add a `__repr__` method that with the details you are requesting. I found example like [this](https://stackoverflow.com/a/58514577) telling but I am happy to change my implementation if it's more relevant

**Comment by kevinmessiaen** [comment]
> @kevinmessiaen I have added utest for `__repr__` to show that we have richer string vs the naming with `__str__`. But if you thing that it is better to also include the class name in `__str__`, I can add it

I don't have a strong opinion on it so we can go without it. But I'm not convinced by having  `name-uuid`, something like `name (uuid)` might be easier to read IMO

**Comment by AdriMarteau** [comment]
> > @kevinmessiaen I have added utest for `__repr__` to show that we have richer string vs the naming with `__str__`. But if you thing that it is better to also include the class name in `__str__`, I can add it
> 
> I don't have a strong opinion on it so we can go without it. But I'm not convinced by having `name-uuid`, something like `name (uuid)` might be easier to read IMO

Very good point let me update this request

**Review by kevinmessiaen — APPROVED** [review]

**Pull request merged**
