### PR TITLE
Add compatibility for python 3.12

### PR DESCRIPTION
**Pull request by Hartorn**
## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Comment by mattbit** [comment]
@Hartorn this seems to work great with vanilla `giskard`, but not when we use the optional group `llm`

**Comment by Hartorn** [comment]
> @Hartorn this seems to work great with vanilla `giskard`, but not when we use the optional group `llm`

I'm looking at it, but I think torch stable is not yet supporting 3.12, so bert score wont be working.
Trying to switch on nightly from torch

**Comment by Hartorn** [comment]
Also, https://github.com/pytorch/text pytorch-text depends on specific torch version 2.1.1
Will not work for python 3.12 I think

**Comment by Hartorn** [comment]
should be arriving soon on stable : https://github.com/pytorch/pytorch/issues/110436

**Pull request merged**
