### PR TITLE
Still upload suite when some artifacts fail to be uploaded

### PR DESCRIPTION
**Pull request by kevinmessiaen**
## Description

Still upload suite when some artifacts fail to be uploaded

## Related Issue

[GSK-2205](feature/gsk-2205-better-handling-of-error-when-uploading-a-suite)

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [x] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
- [ ] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

### CODE REVIEW

**Review by Inokinoki — COMMENTED** [review]
LGTM!

In order to test, how can I have an artifact whose upload can fail?

**Comment by kevinmessiaen** [comment]
> LGTM!
> 
> In order to test, how can I have an artifact whose upload can fail?

Yes what I did is something like that:

```python
class FailingModel(BaseModel):
  def upload(**kwargs):
    raise ValueError("For testing')
```

**Comment by Inokinoki** [comment]
> ```python
> class FailingModel(BaseModel):
>   def upload(**kwargs):
>     raise ValueError("For testing")
> ```

Thanks very much!

I created this test code:

```python
class FailingModel(BaseModel):
    def upload(self, *args, **kwargs):
        raise ValueError("For testing")

    def predict_df(self, *args, **kwargs):
        return 0

test_suite = results.generate_test_suite("Test suite created by scan GSK-2205")

@test
def my_test(model: BaseModel):
    return True

test_suite.add_test(my_test, model=FailingModel(model_type="regression"))

test_suite.upload(client, "titanic")
```

In addition to the failing model, there are the other warnings:

```
Your model is successfully validated.
Model successfully uploaded to project key 'titanic' with ID = a7ffeb37-f100-4caa-bd7d-21ac102481b4
Dataset successfully uploaded to project key 'titanic' with ID = e23c4fb1-7e5e-42f3-bbb8-996e80b225b9
2023-12-26 15:05:49,381 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload Transform to title case used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,486 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Name` contains "mr" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,529 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `text_length(Name)` < 28.500 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,568 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Fare` < 14.850 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,604 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Sex` == "male" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,634 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `avg_word_length(Name)` < 6.292 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,665 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Parch` == 0 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,709 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `avg_whitespace(Name)` >= 0.106 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,738 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `SibSp` == 0 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,765 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Sex` == "female" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,857 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Pclass` == 3 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,886 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Name` contains "master" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,922 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Parch` == 2 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,948 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Embarked` == "S" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:49,973 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Pclass` == 1 used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:50,005 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Name` contains "miss" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:50,140 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload `Embarked` == "Q" used in the test suite. The test suite will be partially uploaded.
2023-12-26 15:05:50,170 pid:7156 MainThread giskard.core.suite WARNING  Failed to upload <__main__.FailingModel object at 0x28b007a30> used in the test suite. The test suite will be partially uploaded.
Test suite has been saved: http://localhost:9000/main/projects/1/test-suite/2/overview
```

I suppose that's because of my `giskard-hub` branch. The exception on the hub side is like:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "params" (class ai.giskard.web.dto.DocumentationDTO), not marked as ignorable (2 known properties: "parameters", "description"])
 at [Source: (String)"{"description":"Automatically generated transformation function","params":{}}"; line: 1, column: 76] (through reference chain: ai.giskard.web.dto.DocumentationDTO["params"])
```

After creating a `Suite` from scratch, it is working as expected:

```
2023-12-26 15:17:42,970 pid:7547 MainThread giskard.core.suite WARNING  Failed to upload <__main__.FailingModel object at 0x17603a2f0> used in the test suite. The test suite will be partially uploaded.
Test suite has been saved: http://localhost:9000/main/projects/1/test-suite/4/overview
```

**Review by Inokinoki — APPROVED** [review]
Would you like to improve the code coverage in `giskard/code/suite.py` in this PR?
Otherwise, let's create a card for this later.

**Pull request merged**
